/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisvelasco' at '19/01/16 9:11' with Gradle 2.6
 *
 * @author luisvelasco, @date 19/01/16 9:11
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
